#!/bin/bash

## Sync
# Init DerpFest repos
repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 14 --depth=1 --git-lfs

# Sync
repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc --all) --optimized-fetch --prune

# Apply personal patches
APPLY_PATCHES=true . build/envsetup.sh
